<?php
  include_once("fest.php");
  A_Check('SysAdmin');
  global $FESTSYS,$VERSION;
  dostaffhead("System Data Settings");

  $FESTSYS = Gen_Get('SystemData',1);
  if (isset($_REQUEST['ACTION'])) {
    switch ($_REQUEST['ACTION']) {
      case 'Update':
        if (UpdateMany('SystemData','',$FESTSYS,0))  $FESTSYS = Gen_Get('SystemData',1);

        Feature_Reset();
        $txt = ":root {\n--main-col:" . Feature('CSSColourMain','#fcb900') . ";\n";
        $txt .= "--main-col-dark:" . Feature('CSSColourDark','#993300') . ";\n";
        $txt .= "--main-contrast:" . Feature('CSSColourContrast','#1a0000') . ";\n}\n";
        $txt .= '/* Do not edit this file it is dynamically created - edit system data or the Basestyle.css*/\n\n';

        $Css = file_get_contents('files/Basestyle.css');

        $txt .= $Css;
        file_put_contents('cache/Style.css',$txt);

        echo "Data and CSS updated<p>";
    }
  }

  echo "<h2>System Data Settings and Global Actions</h2>\n";

//var_dump($_REQUEST);

  if (isset($_REQUEST['Update'])) Update_db_post('SystemData',$FESTSYS);
  echo "<form method=post>\n";
//  Register_AutoUpdate('SystemData',1); - Switching to an Update button
  echo "<div class=tablecont><table>";
  echo "<tr>" . fm_textarea("Features",$FESTSYS,'Features',6,40);
  if (Access('Internal')) {
    echo "<tr>" . fm_textarea("Capabilities",$FESTSYS,'Capabilities',6,10);
    echo "<tr>" . fm_text('Update Version #',$FESTSYS,'CurVersion') . "<td>Never edit";
    echo "<tr>" . fm_text('Version Changed',$FESTSYS,'VersionDate') . "<td>Never edit";
  }
  echo "<tr>" . fm_textarea("Analytics code",$FESTSYS,'Analytics',3,3);

  if (Access('SysAdmin')) echo "<tr><td class=NotSide>Debug<td colspan=6 class=NotSide><textarea id=Debug></textarea>";
  echo "<tr>" . fm_submit('ACTION','Update');
  echo "</table></div>\n";

  echo "</form>\n";

/*  $feet = $FESTSYS['Features'];

  $Dat = parse_ini_string($feet);

  var_dump($Dat);*/

  echo "Features: are in php ini format.<br>; Comments start with ';', as in php.ini<p>";
  dotail();

?>
