CREATE TABLE `Articles` (
  `id` int NOT NULL AUTO_INCREMENT,
  `SN` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Type` smallint NOT NULL,
  `Link` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Image` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `ImageHeight` int NOT NULL,
  `ImageWidth` int NOT NULL,
  `Importance` tinyint NOT NULL,
  `StartDate` int NOT NULL,
  `StopDate` int NOT NULL,
  `Format` tinyint NOT NULL,
  `UsedOn` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `HideTitle` tinyint NOT NULL,
  `RedTitle` tinyint NOT NULL,
  `RelOrder` int NOT NULL,
  `ExternalLink` tinyint NOT NULL,
  `ColSet` int NOT NULL DEFAULT '3',
  `TitleColour` text COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
