CREATE TABLE `EventTypes` (
  `ETypeNo` int NOT NULL AUTO_INCREMENT,
  `SN` text NOT NULL,
  `Plural` text NOT NULL,
  `Public` tinyint NOT NULL,
  `HasDance` tinyint NOT NULL,
  `HasMusic` tinyint NOT NULL,
  `HasOther` tinyint NOT NULL,
  `NotCrit` tinyint NOT NULL,
  `UseImp` tinyint NOT NULL,
  `Format` int NOT NULL,
  `State` tinyint NOT NULL,
  `IncType` tinyint NOT NULL,
  `NoPart` tinyint NOT NULL,
  `DontList` tinyint NOT NULL,
  `FirstYear` text NOT NULL,
  `Banner` text NOT NULL,
  `MapFeatNum` int NOT NULL,
  `IsConcert` tinyint NOT NULL,
  `Importance` int NOT NULL,
  `Sherlock` text NOT NULL,
  `HasRolls` tinyint NOT NULL,
  PRIMARY KEY (`ETypeNo`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3;
