CREATE TABLE `EventTypes` (
  `ETypeNo` int NOT NULL AUTO_INCREMENT,
  `SN` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Plural` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Public` tinyint NOT NULL,
  `HasDance` tinyint NOT NULL,
  `HasMusic` tinyint NOT NULL,
  `HasOther` tinyint NOT NULL,
  `NotCrit` tinyint NOT NULL,
  `UseImp` tinyint NOT NULL,
  `Format` int NOT NULL,
  `State` tinyint NOT NULL,
  `IncType` tinyint NOT NULL,
  `NoPart` tinyint NOT NULL,
  `DontList` tinyint NOT NULL,
  `FirstYear` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Banner` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `MapFeatNum` int NOT NULL,
  `IsConcert` tinyint NOT NULL,
  `Importance` int NOT NULL,
  `Sherlock` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `HasRolls` tinyint NOT NULL,
  PRIMARY KEY (`ETypeNo`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
