CREATE TABLE `FestUsers` (
  `UserId` int NOT NULL AUTO_INCREMENT,
  `Login` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `password` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `AccessLevel` int NOT NULL,
  `Roll` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `SN` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Abrev` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Email` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Phone` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Docs` tinyint NOT NULL,
  `Dance` tinyint NOT NULL,
  `Music` tinyint NOT NULL,
  `Trade` tinyint NOT NULL,
  `Users` tinyint NOT NULL,
  `Venues` tinyint NOT NULL,
  `Sponsors` tinyint NOT NULL,
  `Finance` tinyint NOT NULL,
  `Craft` tinyint NOT NULL,
  `Other` tinyint NOT NULL,
  `TLine` tinyint NOT NULL,
  `Bugs` tinyint NOT NULL,
  `Photos` tinyint NOT NULL,
  `Comedy` tinyint NOT NULL,
  `Family` tinyint NOT NULL,
  `News` tinyint NOT NULL,
  `ChangeSent` int NOT NULL,
  `AccessKey` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `LastAccess` int NOT NULL,
  `Yale` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Image` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `FestEmail` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Contacts` tinyint NOT NULL,
  `NoTasks` tinyint NOT NULL,
  `Prefs` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `LogUse` tinyint NOT NULL,
  `RelOrder` int NOT NULL,
  `ClassEmail` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  PRIMARY KEY (`UserId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
