CREATE TABLE `FoodAndDrink` (
  `id` int NOT NULL AUTO_INCREMENT,
  `SN` text COLLATE latin1_general_ci NOT NULL,
  `Website` text COLLATE latin1_general_ci NOT NULL,
  `PostCode` text COLLATE latin1_general_ci NOT NULL,
  `Phone` text COLLATE latin1_general_ci NOT NULL,
  `Photo` text COLLATE latin1_general_ci NOT NULL,
  `Lat` text COLLATE latin1_general_ci NOT NULL,
  `Lng` text COLLATE latin1_general_ci NOT NULL,
  `Description` text COLLATE latin1_general_ci NOT NULL,
  `Address` text COLLATE latin1_general_ci NOT NULL,
  `Vegan` tinyint NOT NULL,
  `Year` text COLLATE latin1_general_ci NOT NULL,
  `Vegetarian` tinyint NOT NULL,
  `Food` tinyint NOT NULL,
  `Drink` tinyint NOT NULL,
  `Notes` text COLLATE latin1_general_ci NOT NULL,
  `Importance` int NOT NULL,
  `MapImp` int NOT NULL,
  `Directions` text COLLATE latin1_general_ci NOT NULL,
  `Type` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
