CREATE TABLE `General` (
  `id` int NOT NULL AUTO_INCREMENT,
  `Year` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Version` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Freeze` tinyint NOT NULL,
  `DanceProgAvail` tinyint NOT NULL,
  `MusicProgAvail` int NOT NULL,
  `SideProgLevel` tinyint NOT NULL,
  `ActProgLevel` tinyint NOT NULL,
  `OtherProgLevel` tinyint NOT NULL,
  `DanceState` smallint NOT NULL,
  `MusicState` smallint NOT NULL,
  `OtherState` smallint NOT NULL,
  `TradeState` smallint NOT NULL,
  `StewardState` smallint NOT NULL,
  `DateFri` int NOT NULL,
  `MonthFri` int NOT NULL,
  `FirstDay` int NOT NULL,
  `LastDay` int NOT NULL,
  `TradeDates` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `PriceChange1` int NOT NULL,
  `PriceChange2` int NOT NULL,
  `PriceComplete_4` tinyint NOT NULL,
  `PriceComplete_3` tinyint NOT NULL,
  `PriceComplete_2` tinyint NOT NULL,
  `PriceComplete_1` tinyint NOT NULL,
  `PriceComplete0` tinyint NOT NULL,
  `PriceComplete1` tinyint NOT NULL,
  `PriceComplete2` tinyint NOT NULL,
  `PriceComplete3` tinyint NOT NULL,
  `PriceComplete4` tinyint NOT NULL,
  `PriceComplete5` tinyint NOT NULL,
  `PriceComplete6` tinyint NOT NULL,
  `PriceComplete7` tinyint NOT NULL,
  `PriceComplete8` tinyint NOT NULL,
  `PriceComplete9` tinyint NOT NULL,
  `PriceComplete10` tinyint NOT NULL,
  `FamilyState` tinyint NOT NULL,
  `SpecialState` tinyint NOT NULL,
  `SatDanceStart` int NOT NULL,
  `SunDanceStart` int NOT NULL,
  `SatDanceEnd` int NOT NULL,
  `SunDanceEnd` int NOT NULL,
  `SatMusicStart` int NOT NULL,
  `SunMusicStart` int NOT NULL,
  `SatMusicEnd` int NOT NULL,
  `SunMusicEnd` int NOT NULL,
  `FriMusicStart` int NOT NULL,
  `FriMusicEnd` int NOT NULL,
  `TicketControl` tinyint NOT NULL,
  `CampingControl` tinyint NOT NULL,
  `Prefix` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `WeekendPass` int NOT NULL,
  `FridayPass` int NOT NULL,
  `SaturdayPass` int NOT NULL,
  `SundayPass` int NOT NULL,
  `MondayPass` int NOT NULL,
  `WeekendPass1` int NOT NULL,
  `FridayPass1` int NOT NULL,
  `SaturdayPass1` int NOT NULL,
  `SundayPass1` int NOT NULL,
  `MondayPass1` int NOT NULL,
  `WeekendPass2` int NOT NULL,
  `FridayPass2` int NOT NULL,
  `SaturdayPass2` int NOT NULL,
  `SundayPass2` int NOT NULL,
  `MondayPass2` int NOT NULL,
  `ProgrammeBook` int NOT NULL,
  `CampingCost` int NOT NULL,
  `CampingPrice1Day` int NOT NULL,
  `BookingFee` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `CampingGateFee` int NOT NULL,
  `CampingPrice2Day` int NOT NULL,
  `CampingPrice3Day` int NOT NULL,
  `CampingPrice4Day` int NOT NULL,
  `WeekendPassCode` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `FridayPassCode` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `SaturdayPassCode` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `SundayPassCode` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `NotUsed` int NOT NULL,
  `CampingCode_TFSS` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `CampingCode_TFSx` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `CampingCode_TFxx` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `CampingCode_Txxx` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `CampingCode_xFxx` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `CampingCode_xFSS` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `CampingCode_xFSx` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `CampingCode_xxSx` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `CampingCode_xxSS` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `CampingCode_xxxS` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `TradeMainDate` int NOT NULL,
  `TradeLastDate` int NOT NULL,
  `WeekendText` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `FridayText` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `SaturdayText` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `SundayText` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `MondayText` text COLLATE utf8mb4_general_ci NOT NULL,
  `Years2Show` tinyint NOT NULL,
  `NextFest` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `PrevFest` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `FestFeatures` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
