CREATE TABLE `Invoices` (
  `id` int NOT NULL AUTO_INCREMENT,
  `State` tinyint NOT NULL,
  `BZ` text COLLATE latin1_general_ci,
  `Contact` text COLLATE latin1_general_ci,
  `Email` text COLLATE latin1_general_ci NOT NULL,
  `Phone` text COLLATE latin1_general_ci NOT NULL,
  `Mobile` text COLLATE latin1_general_ci NOT NULL,
  `Address` text COLLATE latin1_general_ci NOT NULL,
  `PostCode` text COLLATE latin1_general_ci NOT NULL,
  `IssueDate` int NOT NULL,
  `EmailDate` int NOT NULL,
  `DueDate` int NOT NULL,
  `PayDate` int NOT NULL,
  `InvoiceCode` int NOT NULL,
  `InvoiceCode2` int NOT NULL,
  `InvoiceCode3` int NOT NULL,
  `OurRef` text COLLATE latin1_general_ci NOT NULL,
  `YourRef` text COLLATE latin1_general_ci NOT NULL,
  `Total` int NOT NULL,
  `PaidTotal` int NOT NULL,
  `Desc1` text COLLATE latin1_general_ci NOT NULL,
  `Amount1` int NOT NULL,
  `Desc2` text COLLATE latin1_general_ci NOT NULL,
  `Amount2` int NOT NULL,
  `Desc3` text COLLATE latin1_general_ci NOT NULL,
  `Amount3` int NOT NULL,
  `Source` int NOT NULL,
  `History` text COLLATE latin1_general_ci NOT NULL,
  `Year` text COLLATE latin1_general_ci NOT NULL,
  `SourceId` int NOT NULL,
  `Reason` text COLLATE latin1_general_ci NOT NULL,
  `CNReason` text COLLATE latin1_general_ci NOT NULL,
  `Revision` int NOT NULL,
  `CoverNote` text COLLATE latin1_general_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
