CREATE TABLE `Invoices` (
  `id` int NOT NULL AUTO_INCREMENT,
  `State` tinyint NOT NULL,
  `BZ` text,
  `Contact` text,
  `Email` text NOT NULL,
  `Phone` text NOT NULL,
  `Mobile` text NOT NULL,
  `Address` text NOT NULL,
  `PostCode` text NOT NULL,
  `IssueDate` int NOT NULL,
  `EmailDate` int NOT NULL,
  `DueDate` int NOT NULL,
  `PayDate` int NOT NULL,
  `InvoiceCode` int NOT NULL,
  `InvoiceCode2` int NOT NULL,
  `InvoiceCode3` int NOT NULL,
  `OurRef` text NOT NULL,
  `YourRef` text NOT NULL,
  `Total` int NOT NULL,
  `PaidTotal` int NOT NULL,
  `Desc1` text NOT NULL,
  `Amount1` int NOT NULL,
  `Desc2` text NOT NULL,
  `Amount2` int NOT NULL,
  `Desc3` text NOT NULL,
  `Amount3` int NOT NULL,
  `Source` int NOT NULL,
  `History` text NOT NULL,
  `Year` text NOT NULL,
  `SourceId` int NOT NULL,
  `Reason` text NOT NULL,
  `CNReason` text NOT NULL,
  `Revision` int NOT NULL,
  `CoverNote` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
