CREATE TABLE `Sides` (
  `SideId` int NOT NULL AUTO_INCREMENT,
  `SN` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `ShortName` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Category` tinyint NOT NULL,
  `IsASide` tinyint NOT NULL,
  `IsAnAct` tinyint NOT NULL,
  `IsOther` tinyint NOT NULL,
  `IsFunny` tinyint NOT NULL,
  `IsFamily` tinyint NOT NULL,
  `IsCeilidh` tinyint NOT NULL,
  `IsNonPerf` tinyint NOT NULL,
  `Importance` int NOT NULL,
  `DiffImportance` tinyint NOT NULL,
  `DanceImportance` tinyint NOT NULL,
  `MusicImportance` tinyint NOT NULL,
  `OtherImportance` tinyint NOT NULL,
  `ComedyImportance` tinyint NOT NULL,
  `FamilyImportance` tinyint NOT NULL,
  `CeilidhImportance` tinyint NOT NULL,
  `Type` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `HasAgent` tinyint NOT NULL,
  `BookDirect` tinyint NOT NULL,
  `AgentName` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `AgentEmail` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `AgentPhone` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `AgentMobile` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `AgentAddress` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `AgentPostCode` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Contact` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Email` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Phone` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Mobile` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Address` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `PostCode` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `AltContact` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `AltEmail` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `AltPhone` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `AltMobile` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Location` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Likes` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Dislikes` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `DataCheck` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Notes` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `SideStatus` smallint NOT NULL,
  `Workshops` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Surface_Tarmac` tinyint(1) NOT NULL,
  `Surface_Flagstones` tinyint(1) NOT NULL,
  `Surface_Grass` tinyint(1) NOT NULL,
  `Surface_Stage` tinyint(1) NOT NULL,
  `Surface_Brick` tinyint NOT NULL,
  `Surface_Wood` tinyint NOT NULL,
  `Surface_Carpet` tinyint NOT NULL,
  `Surface_Astroturf` tinyint NOT NULL,
  `StagePA` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `MorrisAnimal` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Photo` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `ImageHeight` int NOT NULL,
  `ImageWidth` int NOT NULL,
  `Video` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `CostumeDesc` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Description` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Blurb` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Website` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Facebook` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Twitter` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Instagram` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `ProcessionalDance` tinyint(1) NOT NULL,
  `NoiseLevel` tinyint(1) NOT NULL,
  `MinStage` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Overlaps` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `AccessKey` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `PartyTricks` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Pre2017` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Share` tinyint NOT NULL,
  `NeedBank` tinyint NOT NULL,
  `WantCheque` tinyint NOT NULL,
  `SortCode` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Account` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `AccountName` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `DocDirNum` int NOT NULL,
  `RelOrder` int NOT NULL,
  `OneBlurb` tinyint NOT NULL,
  `NotPerformer` tinyint NOT NULL,
  PRIMARY KEY (`SideId`),
  KEY `SideNum` (`SideId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
