CREATE TABLE `SignUp` (
  `id` int NOT NULL AUTO_INCREMENT,
  `SN` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Year` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Activity` int NOT NULL,
  `State` tinyint NOT NULL DEFAULT '0',
  `Contact` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Address` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `PostCode` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Email` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Phone` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Style` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Songs` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Equipment` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `FolkFest` tinyint NOT NULL,
  `FFFri` tinyint NOT NULL,
  `FFSat` tinyint NOT NULL,
  `FFSun` tinyint NOT NULL,
  `AccessKey` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Notes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Name1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Name2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Name3` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Name4` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Name5` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Name6` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Instr1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Instr2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Instr3` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Instr4` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Instr5` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Instr6` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `TotalSize` int NOT NULL,
  `Tickbox` tinyint NOT NULL,
  `Example` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Avail1` tinyint NOT NULL,
  `Avail2` tinyint NOT NULL,
  `Avail3` tinyint NOT NULL,
  `Bio` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Started` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Social` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Website` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Tickbox1` tinyint NOT NULL,
  `Tickbox2` tinyint NOT NULL,
  `Tickbox3` tinyint NOT NULL,
  `Tickbox4` tinyint NOT NULL,
  `Tickbox5` tinyint NOT NULL,
  `Tickbox6` tinyint NOT NULL,
  `Age` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Discount` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
