CREATE TABLE `TimeLine` (
  `TLid` int NOT NULL AUTO_INCREMENT,
  `Title` text NOT NULL,
  `Progress` int NOT NULL,
  `Assigned` int NOT NULL,
  `Created` int NOT NULL,
  `Completed` int NOT NULL,
  `CreatedBy` int NOT NULL,
  `Start` int NOT NULL,
  `Due` int NOT NULL,
  `Notes` text NOT NULL,
  `Year` int NOT NULL,
  `NextYearId` int NOT NULL,
  `Progtext` text NOT NULL,
  `History` text NOT NULL,
  `Importance` tinyint NOT NULL,
  `Recuring` tinyint NOT NULL,
  `DependsOn1` int NOT NULL,
  `DependsOn2` int NOT NULL,
  `DependsOn3` int NOT NULL,
  `DependsOn4` int NOT NULL,
  PRIMARY KEY (`TLid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3;
