CREATE TABLE `TimeLine` (
  `TLid` int NOT NULL AUTO_INCREMENT,
  `Title` text COLLATE utf8mb4_general_ci,
  `Progress` int NOT NULL,
  `Assigned` int NOT NULL,
  `Created` int NOT NULL,
  `Completed` int NOT NULL,
  `CreatedBy` int NOT NULL,
  `Start` int NOT NULL,
  `Due` int NOT NULL,
  `Notes` text COLLATE utf8mb4_general_ci,
  `Year` text COLLATE utf8mb4_general_ci,
  `NextYearId` int NOT NULL,
  `Progtext` text COLLATE utf8mb4_general_ci,
  `History` text COLLATE utf8mb4_general_ci,
  `Importance` tinyint NOT NULL,
  `Recuring` tinyint NOT NULL,
  `DependsOn1` int NOT NULL,
  `DependsOn2` int NOT NULL,
  `DependsOn3` int NOT NULL,
  `DependsOn4` int NOT NULL,
  PRIMARY KEY (`TLid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
