CREATE TABLE `TimeLine` (
  `TLid` int NOT NULL AUTO_INCREMENT,
  `Title` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Progress` int NOT NULL,
  `Assigned` int NOT NULL,
  `Created` int NOT NULL,
  `Completed` int NOT NULL,
  `CreatedBy` int NOT NULL,
  `Start` int NOT NULL,
  `Due` int NOT NULL,
  `Notes` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Year` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `NextYearId` int NOT NULL,
  `Progtext` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `History` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Importance` tinyint NOT NULL,
  `Recuring` tinyint NOT NULL,
  `DependsOn1` int NOT NULL,
  `DependsOn2` int NOT NULL,
  `DependsOn3` int NOT NULL,
  `DependsOn4` int NOT NULL,
  PRIMARY KEY (`TLid`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
