CREATE TABLE `TradeYear` (
  `TYid` int NOT NULL AUTO_INCREMENT,
  `Tid` int NOT NULL,
  `Year` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Days` tinyint NOT NULL,
  `Insurance` tinyint NOT NULL,
  `RiskAssessment` tinyint NOT NULL,
  `HealthChecked` tinyint NOT NULL,
  `PitchSize0` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `PitchSize1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `PitchSize2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Power0` int NOT NULL,
  `Power1` int NOT NULL,
  `Power2` int NOT NULL,
  `PitchNum0` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `PitchNum1` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `PitchNum2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `PitchLoc0` smallint NOT NULL,
  `PitchLoc1` smallint NOT NULL,
  `PitchLoc2` smallint NOT NULL,
  `BookingState` tinyint NOT NULL,
  `Fee` int NOT NULL,
  `TotalPaid` int NOT NULL,
  `YNotes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `PNotes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Date` int NOT NULL,
  `History` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `SentInvite` int NOT NULL,
  `SentConfirm` int NOT NULL,
  `SentLocation` int NOT NULL,
  `SentArrive` int NOT NULL,
  `DepositCode` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `BalanceCode` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `OtherCode` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `DateChange` int NOT NULL,
  `QuoteSize0` text COLLATE utf8mb4_general_ci NOT NULL,
  `QuoteSize1` text COLLATE utf8mb4_general_ci NOT NULL,
  `QuoteSize2` text COLLATE utf8mb4_general_ci NOT NULL,
  `Tables0` int NOT NULL,
  `Tables1` int NOT NULL,
  `Tables2` int NOT NULL,
  `ExtraPower` int NOT NULL,
  `ExtraPowerNumber` int NOT NULL,
  `ExtraPowerCost` int NOT NULL DEFAULT '0',
  `ExtraPowerDesc` text COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`TYid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
