CREATE TABLE `TradePrices` (
  `id` int NOT NULL AUTO_INCREMENT,
  `SN` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `ListOrder` int NOT NULL,
  `Colour` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `BasePrice` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `PerDay` tinyint NOT NULL,
  `Deposit` int NOT NULL,
  `Addition` tinyint NOT NULL,
  `NeedCharityNum` tinyint NOT NULL,
  `NeedPublicHealth` tinyint NOT NULL,
  `NeedInsurance` tinyint NOT NULL,
  `NeedRiskAssess` tinyint NOT NULL,
  `ArtisanMsgs` tinyint NOT NULL,
  `TOpen` tinyint NOT NULL,
  `Description` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `SalesCode` int NOT NULL,
  `DefaultSize` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
