CREATE TABLE `Trade` (
  `Tid` int NOT NULL AUTO_INCREMENT,
  `SN` text COLLATE utf8mb4_general_ci,
  `BizName` text COLLATE utf8mb4_general_ci,
  `IsTrader` tinyint NOT NULL,
  `IsSponsor` tinyint NOT NULL,
  `IsAdvertiser` tinyint NOT NULL,
  `IsSupplier` tinyint NOT NULL,
  `IsOther` tinyint NOT NULL,
  `Status` tinyint NOT NULL,
  `Contact` text COLLATE utf8mb4_general_ci,
  `Email` text COLLATE utf8mb4_general_ci,
  `Website` text COLLATE utf8mb4_general_ci,
  `ListMe` tinyint NOT NULL,
  `Photo` text COLLATE utf8mb4_general_ci,
  `Logo` text COLLATE utf8mb4_general_ci,
  `GoodsDesc` text COLLATE utf8mb4_general_ci,
  `Phone` text COLLATE utf8mb4_general_ci,
  `Mobile` text COLLATE utf8mb4_general_ci,
  `TradeType` tinyint NOT NULL,
  `Charity` text COLLATE utf8mb4_general_ci,
  `BID` tinyint NOT NULL,
  `ChamberTrade` tinyint NOT NULL,
  `Previous` tinyint NOT NULL,
  `RefCode` text COLLATE utf8mb4_general_ci,
  `Address` text COLLATE utf8mb4_general_ci,
  `PostCode` text COLLATE utf8mb4_general_ci,
  `Notes` text COLLATE utf8mb4_general_ci,
  `AccessKey` text COLLATE utf8mb4_general_ci,
  `PublicHealth` text COLLATE utf8mb4_general_ci,
  `SageCode` text COLLATE utf8mb4_general_ci,
  `SortCode` text COLLATE utf8mb4_general_ci,
  `Account` text COLLATE utf8mb4_general_ci,
  `AccountName` text COLLATE utf8mb4_general_ci,
  `IandT` tinyint NOT NULL,
  PRIMARY KEY (`Tid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
