CREATE TABLE `TradeYear` (
  `TYid` int NOT NULL AUTO_INCREMENT,
  `Tid` int NOT NULL,
  `Year` text COLLATE utf8mb4_general_ci,
  `Days` tinyint NOT NULL,
  `Insurance` tinyint NOT NULL,
  `RiskAssessment` tinyint NOT NULL,
  `HealthChecked` tinyint NOT NULL,
  `PitchSize0` text COLLATE utf8mb4_general_ci,
  `PitchSize1` text COLLATE utf8mb4_general_ci,
  `PitchSize2` text COLLATE utf8mb4_general_ci,
  `Power0` int NOT NULL,
  `Power1` int NOT NULL,
  `Power2` int NOT NULL,
  `PitchNum0` text COLLATE utf8mb4_general_ci,
  `PitchNum1` text COLLATE utf8mb4_general_ci,
  `PitchNum2` text COLLATE utf8mb4_general_ci,
  `PitchLoc0` smallint NOT NULL,
  `PitchLoc1` smallint NOT NULL,
  `PitchLoc2` smallint NOT NULL,
  `BookingState` tinyint NOT NULL,
  `Fee` int NOT NULL,
  `TotalPaid` int NOT NULL,
  `YNotes` text COLLATE utf8mb4_general_ci,
  `PNotes` text COLLATE utf8mb4_general_ci,
  `Date` int NOT NULL,
  `History` text COLLATE utf8mb4_general_ci,
  `SentInvite` int NOT NULL,
  `SentConfirm` int NOT NULL,
  `SentLocation` int NOT NULL,
  `SentArrive` int NOT NULL,
  `DepositCode` text COLLATE utf8mb4_general_ci,
  `BalanceCode` text COLLATE utf8mb4_general_ci,
  `OtherCode` text COLLATE utf8mb4_general_ci,
  `DateChange` int NOT NULL,
  PRIMARY KEY (`TYid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
