CREATE TABLE `Trade` (
  `Tid` int NOT NULL AUTO_INCREMENT,
  `SN` text,
  `BizName` text NOT NULL,
  `IsTrader` tinyint NOT NULL,
  `IsSponsor` tinyint NOT NULL,
  `IsAdvertiser` tinyint NOT NULL,
  `IsSupplier` tinyint NOT NULL,
  `IsOther` tinyint NOT NULL,
  `Status` tinyint NOT NULL,
  `Contact` text NOT NULL,
  `Email` text NOT NULL,
  `Website` text NOT NULL,
  `ListMe` tinyint NOT NULL,
  `Photo` text NOT NULL,
  `Logo` text NOT NULL,
  `GoodsDesc` text NOT NULL,
  `Phone` text NOT NULL,
  `Mobile` text NOT NULL,
  `TradeType` tinyint NOT NULL,
  `Charity` text NOT NULL,
  `BID` tinyint NOT NULL,
  `ChamberTrade` tinyint NOT NULL,
  `Previous` tinyint NOT NULL,
  `RefCode` text NOT NULL,
  `Address` text NOT NULL,
  `PostCode` text NOT NULL,
  `Notes` text NOT NULL,
  `AccessKey` text NOT NULL,
  `PublicHealth` text NOT NULL,
  `SageCode` text NOT NULL,
  `SortCode` text NOT NULL,
  `Account` text NOT NULL,
  `AccountName` text NOT NULL,
  PRIMARY KEY (`Tid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3;
