CREATE TABLE `TradePrices` (
  `id` int NOT NULL AUTO_INCREMENT,
  `SN` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `ListOrder` int NOT NULL,
  `Colour` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `BasePrice` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `PerDay` tinyint NOT NULL,
  `Deposit` int NOT NULL,
  `Addition` tinyint NOT NULL,
  `NeedCharityNum` tinyint NOT NULL,
  `NeedPublicHealth` tinyint NOT NULL,
  `NeedInsurance` tinyint NOT NULL,
  `NeedRiskAssess` tinyint NOT NULL,
  `ArtisanMsgs` tinyint NOT NULL,
  `TOpen` tinyint NOT NULL,
  `Description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `SalesCode` int NOT NULL,
  `DefaultSize` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
