CREATE TABLE `Trade` (
  `Tid` int NOT NULL AUTO_INCREMENT,
  `SN` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `BizName` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `IsTrader` tinyint NOT NULL,
  `IsSponsor` tinyint NOT NULL,
  `IsAdvertiser` tinyint NOT NULL,
  `IsSupplier` tinyint NOT NULL,
  `IsOther` tinyint NOT NULL,
  `Status` tinyint NOT NULL,
  `Contact` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Email` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Website` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `ListMe` tinyint NOT NULL,
  `Photo` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Logo` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `GoodsDesc` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Phone` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Mobile` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `TradeType` tinyint NOT NULL,
  `Charity` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `BID` tinyint NOT NULL,
  `ChamberTrade` tinyint NOT NULL,
  `Previous` tinyint NOT NULL,
  `RefCode` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Address` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `PostCode` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Notes` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `AccessKey` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `PublicHealth` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `SageCode` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `SortCode` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Account` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `AccountName` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `IandT` tinyint NOT NULL,
  PRIMARY KEY (`Tid`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
