CREATE TABLE `Venues` (
  `ShortName` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `SN` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `VenueId` int NOT NULL AUTO_INCREMENT,
  `Notes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Status` tinyint NOT NULL,
  `SetupOverlap` tinyint NOT NULL,
  `AllowMult` tinyint NOT NULL,
  `Dance` tinyint NOT NULL,
  `Music` tinyint NOT NULL,
  `Comedy` tinyint NOT NULL,
  `Child` tinyint NOT NULL,
  `Ceilidh` tinyint NOT NULL,
  `Craft` tinyint NOT NULL,
  `Other` tinyint NOT NULL,
  `DanceImportance` int NOT NULL,
  `MusicImportance` int NOT NULL,
  `OtherImportance` int NOT NULL,
  `SurfaceType1` tinyint NOT NULL,
  `SurfaceType2` tinyint NOT NULL,
  `MinorFri` tinyint NOT NULL,
  `MinorSat` tinyint NOT NULL,
  `MinorSun` tinyint NOT NULL,
  `MinorMon` int NOT NULL,
  `Address` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `PostCode` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `DirectionsExtra` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `DanceRider` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `MusicRider` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `OtherRider` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `BudgetHeading` smallint NOT NULL,
  `Parking` tinyint NOT NULL,
  `Image` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Caption` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Image2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Caption2` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Lat` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Lng` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `IconType` int NOT NULL,
  `MapImp` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Food` tinyint NOT NULL,
  `Bar` tinyint NOT NULL,
  `BarFoodText` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Website` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `PartVirt` int NOT NULL,
  `IsVirtual` tinyint NOT NULL,
  `DontUseIf` int NOT NULL,
  `SupressFree` tinyint NOT NULL,
  `DisabilityStat` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `AccessKey` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Complete` int NOT NULL,
  `Banner` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `SponsoredBy` int NOT NULL,
  `SponsorYear` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `3Words` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `SuppressParent` tinyint NOT NULL,
  PRIMARY KEY (`VenueId`),
  UNIQUE KEY `VenueId` (`VenueId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
