CREATE TABLE `VolCats` (
  `id` int NOT NULL AUTO_INCREMENT,
  `ShortName` text COLLATE latin1_general_ci NOT NULL,
  `Name` text COLLATE latin1_general_ci NOT NULL,
  `Description` text COLLATE latin1_general_ci NOT NULL,
  `Listofwhen` text COLLATE latin1_general_ci NOT NULL,
  `Email` text COLLATE latin1_general_ci NOT NULL,
  `Props` int NOT NULL,
  `OtherQ1` text COLLATE latin1_general_ci NOT NULL,
  `OtherQ2` text COLLATE latin1_general_ci NOT NULL,
  `OtherQ3` text COLLATE latin1_general_ci NOT NULL,
  `OtherQ4` text COLLATE latin1_general_ci NOT NULL,
  `Q4Extra` text COLLATE latin1_general_ci NOT NULL,
  `LExtra` text COLLATE latin1_general_ci NOT NULL,
  `DExtra` text CHARACTER SET latin1 COLLATE latin1_general_cs NOT NULL,
  `Q1Extra` text COLLATE latin1_general_ci NOT NULL,
  `Q2Extra` text COLLATE latin1_general_ci NOT NULL,
  `Q3Extra` text COLLATE latin1_general_ci NOT NULL,
  `Image` text COLLATE latin1_general_ci NOT NULL,
  `LongDesc` text COLLATE latin1_general_ci NOT NULL,
  `Importance` int NOT NULL,
  `VolName` text COLLATE latin1_general_ci NOT NULL,
  `ImageHeight` int NOT NULL,
  `ImageWidth` int NOT NULL,
  `Colour` text COLLATE latin1_general_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
