CREATE TABLE `Volunteers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `SN` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `Email` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Phone` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Address` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `PostCode` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Over18` tinyint NOT NULL,
  `Birthday` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `ContactName` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `ContactPhone` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `DBS` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `FirstAid` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Relation` smallint NOT NULL,
  `AccessKey` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Status` tinyint NOT NULL,
  `Disabilities` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `KeepMe` int NOT NULL,
  `Photo` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `DBSupload` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `FirstAidUpload` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `OtherUpload` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Money` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
