CREATE TABLE `Volunteers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `SN` text COLLATE utf8mb4_general_ci,
  `Email` text COLLATE utf8mb4_general_ci,
  `Phone` text COLLATE utf8mb4_general_ci,
  `Address` text COLLATE utf8mb4_general_ci,
  `PostCode` text COLLATE utf8mb4_general_ci,
  `Over18` tinyint NOT NULL,
  `Birthday` text COLLATE utf8mb4_general_ci,
  `ContactName` text COLLATE utf8mb4_general_ci,
  `ContactPhone` text COLLATE utf8mb4_general_ci,
  `DBS` text COLLATE utf8mb4_general_ci,
  `FirstAid` text COLLATE utf8mb4_general_ci,
  `Relation` smallint NOT NULL,
  `AccessKey` text COLLATE utf8mb4_general_ci,
  `Status` tinyint NOT NULL,
  `Disabilities` text COLLATE utf8mb4_general_ci,
  `KeepMe` int NOT NULL,
  `Photo` text COLLATE utf8mb4_general_ci,
  `DBSupload` text COLLATE utf8mb4_general_ci,
  `FirstAidUpload` text COLLATE utf8mb4_general_ci,
  `OtherUpload` text COLLATE utf8mb4_general_ci,
  `Money` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
