CREATE TABLE `VolYear` (
  `id` int NOT NULL AUTO_INCREMENT,
  `Volid` int NOT NULL,
  `AvailBefore` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `AvailWeek` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Avail_4` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Avail_3` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Avail_2` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Avail_1` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Avail0` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Avail1` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Avail2` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Avail3` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Avail4` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Avail5` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Avail6` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Avail7` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Avail8` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Avail9` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Avail10` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Avail11` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Year` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Notes` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Status` int NOT NULL,
  `Adults` int NOT NULL DEFAULT '1',
  `Children` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `Youth` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `CampNeed` int NOT NULL,
  `CampType` int NOT NULL,
  `SubmitDate` int NOT NULL,
  `LastUpdate` int NOT NULL,
  `CampText` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `TicketsCollected` int NOT NULL,
  `CollectedBy` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
